services:
  with-docker-multi-env-development:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjstest
    ports:
      - "3000:3000"
    env_file:
      - env/staging.env
