services:
  with-docker-multi-env-development:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=https://pillar-staging-api.smms.com.tw/
      - API_PATH=api
      - API_VERSION=v1
    env_file:
      - env/staging.env
