services:
  with-docker-multi-env-development:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - SOMEENV=HIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
